databases:
  - name: sitedb
    plan: free
    databaseName: data_viz_db
    user: root

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.wsgi:application"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true