# Generated by Django 5.0.2 on 2024-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketpricedata",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="marketpricedata",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
