# Generated by Django 5.0.2 on 2024-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_item_product_productinout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinout',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
