# Generated by Django 5.0.2 on 2024-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productinout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinout',
            name='order_completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
