# Generated by Django 5.0.2 on 2024-02-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productinout_order_completed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinout',
            old_name='status',
            new_name='delivered',
        ),
    ]
