# Generated by Django 5.0.2 on 2024-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_status_productinout_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='KG', max_length=150),
            preserve_default=False,
        ),
    ]
