# Generated by Django 5.0.2 on 2024-02-20 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_inout_productinout_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinout',
            name='order_completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Order Completed On'),
        ),
        migrations.AlterField(
            model_name='productinout',
            name='order_initiated_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Initiated On'),
        ),
        migrations.AlterField(
            model_name='productinout',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Inbound Order'), (2, 'Outbound Order')], default=1, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='productinout',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
    ]
