# Generated by Django 5.0.2 on 2024-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_productinout_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinout',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
