# Generated by Django 5.0.2 on 2024-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_productinout_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinout',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Discount in Taka'),
        ),
        migrations.AddField(
            model_name='productinout',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='total Price'),
        ),
    ]
