# Generated by Django 5.0.2 on 2024-03-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outorder",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
